// Generated by https://pagedraw.io/pages/13121
import React from 'react';
import './webframe.css';


export default class Webframe extends React.Component {
  render() {
    return (
      <div className="webframe-webframe-0">
          <div className="webframe-0">
              <div className="webframe-frameshoeshopp-0">
                  <div className="webframe-0-0-0">
                      <div className="webframe-title-0">
                          <div className="webframe-0-0-0-0-0">
                              <div className="webframe-the_shoes_shopping_store-0">
                                  The Shoes Shopping Store
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-0-1">
                  <div className="webframe-0-1-0">
                      <div className="webframe-0-1-0-0">
                          <div className="webframe-shoesel-0" /> 
                          <div className="webframe-frameshoeselect-0">
                              <div className="webframe-0-1-0-0-1-0">
                                  <div className="webframe-shoe_selections-0">
                                      Shoe Selections
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-framecheckout-0">
                  <div className="webframe-0-2-0">
                      <div className="webframe-checkout-0">
                          <div className="webframe-0-2-0-0-0">
                              <div className="webframe-cart_checkout-0">
                                  Cart Checkout
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-1">
              <div className="webframe-1-0">
                  <div className="webframe-1-0-0">
                      <div className="webframe-frame-0">
                          <div className="webframe-1-0-0-0-0">
                              <div className="webframe-cardbox-0">
                                  <div className="webframe-1-0-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/26920c8a-ca6d-41c8-8688-33d15caacac0/" className="webframe-image_2" /> 
                                  </div>
                                  <div className="webframe-1-0-0-0-0-0-1">
                                      <div className="webframe-price-0">
                                          <div className="webframe-1-0-0-0-0-0-1-0-0">
                                              <div className="webframe-_4">$40.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframe-1-0-0-0-0-0-2">
                                      <div onClick={this.props.onClick} className="webframe-addtocart-0">
                                          <div className="webframe-1-0-0-0-0-0-2-0-0">
                                              <div className="webframe-add_to_cart-0">Add to Cart</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-1-1">
                  <div className="webframe-1-1-0">
                      <div className="webframe-framecard2">
                          <div className="webframe-1-1-0-0-0">
                              <div className="webframe-cardbox-00">
                                  <div className="webframe-1-1-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/7b6e9f3b-97dd-4eb7-ab39-656baceaf87b/" className="webframe-image-9" /> 
                                  </div>
                                  <div className="webframe-1-1-0-0-0-0-1">
                                      <div className="webframe-price-00">
                                          <div className="webframe-1-1-0-0-0-0-1-0-0">
                                              <div className="webframe-_3">$30.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframe-1-1-0-0-0-0-2">
                                      <div onClick={this.props.onClick2} className="webframe-addtocart-00">
                                          <div className="webframe-1-1-0-0-0-0-2-0-0">
                                              <div className="webframe-add_to_cart-00">Add to Cart</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-2">
              <div className="webframe-image_3">
                  <div className="webframe-2-0-0">
                      <div className="webframe-frame_2">
                          <div className="webframe-2-0-0-0-0">
                              <div className="webframe-rectangle_2">
                                  <div className="webframe-2-0-0-0-0-0-0">
                                      <div className="webframe-_0">{ this.props.text }</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
